services:
  broker:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --kafka-addr=0.0.0.0:9092
      - --advertise-kafka-addr=broker:9092
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=broker:33145
      - --pandaproxy-addr=0.0.0.0:8082
      - --advertise-pandaproxy-addr=broker:8082
    ports:
      - "9092:9092"
      - "9644:9644"
      - "8082:8082"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info --brokers=broker:9092 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  normalizer:
    build:
      context: .
      dockerfile: normalizer/Dockerfile
    environment:
      BROKERS: broker:9092
      SCHEMA_URL: http://broker:8081
      IN_TOPIC: ingest.raw.agent
      OUT_TOPIC: signals.metric.v1
    depends_on:
      broker:
        condition: service_healthy
    volumes:
      - data:/data

  enricher:
    build:
      context: .
      dockerfile: enricher/Dockerfile
    environment:
      BROKERS: broker:9092
      IN_TOPIC: signals.metric.v1
      OUT_TOPIC: signals.metric.v1
    depends_on:
      broker:
        condition: service_healthy
    volumes:
      - data:/data

  feature-rules:
    build:
      context: .
      dockerfile: feature-rules/Dockerfile
    environment:
      BROKERS: broker:9092
      IN_TOPIC: signals.metric.v1
      OUT_TOPIC: ops.alert.v1
      PG_HOST: postgres
      PG_PORT: "5432"
      PG_DB: eventops
      PG_USER: eventops
      PG_PASS: secret
    depends_on:
      broker:
        condition: service_healthy
      topics-init:
        condition: service_started
      postgres:
        condition: service_started
    volumes:
      - data:/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      BROKERS: broker:9092
      ALERTS_TOPIC: ops.alert.v1
      PG_HOST: postgres
      PG_PORT: "5432"
      PG_DB: eventops
      PG_USER: eventops
      PG_PASS: secret
      HOST: 0.0.0.0
      PORT: 8088
    ports: ["8088:8088"]
    depends_on:
      broker:
        condition: service_healthy
      topics-init:
        condition: service_started
      postgres:
        condition: service_started
    volumes:
      - data:/data

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: eventops
      POSTGRES_USER: eventops
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

volumes:
  data:
  pgdata:
