version: "3.9"

services:
  broker:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --kafka-addr=0.0.0.0:9092
      - --advertise-kafka-addr=broker:9092
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=broker:33145
      - --pandaproxy-addr=0.0.0.0:8082
      - --advertise-pandaproxy-addr=broker:8082
      - --schema-registry-addr=0.0.0.0:8081
    ports:
      - "9092:9092"
      - "9644:9644"
      - "8081:8081"
      - "8082:8082"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info --brokers=broker:9092 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  topics-init:
    image: redpandadata/redpanda:latest
    depends_on:
      broker:
        condition: service_healthy
    entrypoint: ["/bin/sh","-lc"]
    command: >
      for i in $(seq 1 30); do
        rpk cluster info --brokers=broker:9092 && break || sleep 2;
      done;
      rpk topic create ingest.raw.agent signals.metric.v1 ops.alert.v1 --brokers=broker:9092 || true;
      rpk topic alter-config ops.alert.v1 --set cleanup.policy=compact,delete --brokers=broker:9092 || true;
      echo "Topics ready"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: eventops
      POSTGRES_USER: eventops
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventops -d eventops || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  normalizer:
    build:
      context: .
      dockerfile: normalizer/Dockerfile
    environment:
      BROKERS: broker:9092
      IN_TOPIC: ingest.raw.agent
      OUT_TOPIC: signals.metric.v1
    depends_on:
      broker:
        condition: service_healthy
      topics-init:
        condition: service_started
    volumes:
      - data:/data

  enricher:
    build:
      context: .
      dockerfile: enricher/Dockerfile
    environment:
      BROKERS: broker:9092
      IN_TOPIC: signals.metric.v1
      OUT_TOPIC: signals.metric.v1
    depends_on:
      broker:
        condition: service_healthy
      topics-init:
        condition: service_started
    volumes:
      - data:/data

  feature-rules:
    build:
      context: .
      dockerfile: feature-rules/Dockerfile
    environment:
      BROKERS: broker:9092
      IN_TOPIC: signals.metric.v1
      OUT_TOPIC: ops.alert.v1
      PG_HOST: postgres
      PG_PORT: "5432"
      PG_DB: eventops
      PG_USER: eventops
      PG_PASS: secret
    depends_on:
      broker:
        condition: service_healthy
      topics-init:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - data:/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      BROKERS: broker:9092
      ALERTS_TOPIC: ops.alert.v1
      PG_HOST: postgres
      PG_PORT: "5432"
      PG_DB: eventops
      PG_USER: eventops
      PG_PASS: secret
      HOST: 0.0.0.0
      PORT: 8088
    ports:
      - "8088:8088"
    depends_on:
      broker:
        condition: service_healthy
      topics-init:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - data:/data

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  data:
  pgdata:
